AWSTemplateFormatVersion: '2010-09-09'
Description: Parametri per Workshop su CloudFormation

Parameters:
  AMI:
    Description: Amazon Machine Image ID
    Type: String
    Default: "ami-08541bb85074a743a"  

  InstanceType:
    Description: Type of EC2 instance
    Type: String
    Default: "t3.micro" 
    AllowedValues:
      - "t2.micro"
      - "t2.small"
      - "t3.micro"
      - "t3.small"
      
